app/models.py
from app import db
from datetime import datetime

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Stirng(140))
    stug = db.Column(db.Sting(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())
    

app/app.py
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from posts.blueprint import posts



app = Flask(__name__)
app.config.from_object(Configuration) #передаем переменные из другого объекста в данном случае это debug=true (добавление идет в словарь from_object)

db = SQLAlchemy(app)

app.register_blueprint(posts, url_prefix='/blog')

app/main.py
from app import app
from app import db
import view


if __name__ == '__main__':
    # app.run(debug=True)
    app.run()



app/posts/blueprint.py
# кyсок изолированной информации - blueprintd
from flask import render_template
from flask import Blueprint
posts = Blueprint('posts', __name__, template_folder='templates')  #posts это имя под которым зарегин blueprint

@posts.route('/')
def index():

    return render_template('posts/index.html')

app/templates/about.html
{% extends "base.html" %}


{% block title %}
    Index page
{% endblock  %}
    


{% block content_title %}
    contitle title
{% endblock  %}
    
{% block content %}
        Somecontent
{% endblock  %}
    

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title>
        {% block title %}

        {% endblock %} | Flask app
    </title>
</head>
<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('index') }}">Flask</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{{ url_for('posts.index') }}">Blog <span class="sr-only">(current)</span></a></li>
                    <li><a href="#">Link</a></li>
                </ul>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#">Link</a></li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
    <div></div>
</body>
<div class="container">
    <div class="row">
<h1>
    {% block content_title %}

    {% endblock%}
</h1>
<h1>
    {% block content %}

    {% endblock %}
</h1>
    </div>
</div>
</body>
</html>

app/templates/contactus.html
{% extends "base.html" %}


{% block title %}
    Index page
{% endblock  %}
    


{% block content_title %}
    contitle title
{% endblock  %}
    
{% block content %}
        Somecontent
{% endblock  %}
    

app/templates/index.html
{% extends "base.html" %}


{% block title %}
    Index page
{% endblock  %}
    


{% block content_title %}
    contitle title
{% endblock  %}
    
{% block content %}
        Somecontent
{% endblock  %}
    